# -*- coding: utf-8 -*-
"""HAJBI-Doaa-iss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udq8QbTdNJ2ICxyszQ3mUv3KYuNiZizL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Charger un dataset en ligne (exemple : ventes d'une entreprise)
#
url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv" #jeux de données
df = pd.read_csv(url)

# Afficher les premières lignes
print(df.head())

# Informations sur le dataset
print(df.info())

# Statistiques descriptives
print(df.describe())

# Statistiques pour une colonne spécifique
colonne = df['Value']  # Adapter selon vos données

print(f"Moyenne: {colonne.mean():.2f}")
print(f"Médiane: {colonne.median():.2f}")
print(f"Mode: {colonne.mode()[0]:.2f}")
print(f"Écart-type: {colonne.std():.2f}")
print(f"Variance: {colonne.var():.2f}")
print(f"Min: {colonne.min():.2f}")
print(f"Max: {colonne.max():.2f}")

# Quartiles
print(f"Q1 (25%): {colonne.quantile(0.25):.2f}")
print(f"Q2 (50% - Médiane): {colonne.quantile(0.50):.2f}")
print(f"Q3 (75%): {colonne.quantile(0.75):.2f}")
print(f"IQR: {colonne.quantile(0.75) - colonne.quantile(0.25):.2f}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Charger un dataset en ligne (exemple : ventes d'une entreprise)
#
url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv" #jeux de données
df = pd.read_csv(url)

# Afficher les premières lignes
print(df.head())

# Informations sur le dataset
print(df.info())

# Statistiques descriptives
print(df.describe())

# Statistiques pour une colonne spécifique
colonne = df['Value']  # Adapter selon vos données

print(f"Moyenne: {colonne.mean():.2f}")
print(f"Médiane: {colonne.median():.2f}")
print(f"Mode: {colonne.mode()[0]:.2f}")
print(f"Écart-type: {colonne.std():.2f}")
print(f"Variance: {colonne.var():.2f}")
print(f"Min: {colonne.min():.2f}")
print(f"Max: {colonne.max():.2f}")

# Quartiles
print(f"Q1 (25%): {colonne.quantile(0.25):.2f}")
print(f"Q2 (50% - Médiane): {colonne.quantile(0.50):.2f}")
print(f"Q3 (75%): {colonne.quantile(0.75):.2f}")
print(f"IQR: {colonne.quantile(0.75) - colonne.quantile(0.25):.2f}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Charger un dataset en ligne (exemple : ventes d'une entreprise)
#
url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv" #jeux de données
df = pd.read_csv(url)

# Afficher les premières lignes
print(df.head())

# Informations sur le dataset
print(df.info())

# Statistiques descriptives
print(df.describe())

# Statistiques pour une colonne spécifique
colonne = df['Value']  # Adapter selon vos données

print(f"Moyenne: {colonne.mean():.2f}")
print(f"Médiane: {colonne.median():.2f}")
print(f"Mode: {colonne.mode()[0]:.2f}")
print(f"Écart-type: {colonne.std():.2f}")
print(f"Variance: {colonne.var():.2f}")
print(f"Min: {colonne.min():.2f}")
print(f"Max: {colonne.max():.2f}")

# Quartiles
print(f"Q1 (25%): {colonne.quantile(0.25):.2f}")
print(f"Q2 (50% - Médiane): {colonne.quantile(0.50):.2f}")
print(f"Q3 (75%): {colonne.quantile(0.75):.2f}")
print(f"IQR: {colonne.quantile(0.75) - colonne.quantile(0.25):.2f}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Charger un dataset en ligne (exemple : ventes d'une entreprise)
# gdp.csv : nom fichier PIB

url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv" #jeux de données
df = pd.read_csv(url)

# Afficher les premières lignes
print(df.head())

# Informations sur le dataset
print(df.info())

# Statistiques descriptives
print(df.describe())

# Statistiques pour une colonne spécifique
colonne = df['Value']  # Adapter selon vos données

print(f"Moyenne: {colonne.mean():.2f}")
print(f"Médiane: {colonne.median():.2f}")
print(f"Mode: {colonne.mode()[0]:.2f}")
print(f"Écart-type: {colonne.std():.2f}")
print(f"Variance: {colonne.var():.2f}")
print(f"Min: {colonne.min():.2f}")
print(f"Max: {colonne.max():.2f}")

# Quartiles
print(f"Q1 (25%): {colonne.quantile(0.25):.2f}")
print(f"Q2 (50% - Médiane): {colonne.quantile(0.50):.2f}")
print(f"Q3 (75%): {colonne.quantile(0.75):.2f}")
print(f"IQR: {colonne.quantile(0.75) - colonne.quantile(0.25):.2f}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Charger un dataset en ligne (exemple : ventes d'une entreprise)
# gdp.csv : nom fichier PIB

url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv" #jeux de données
df = pd.read_csv(url)

# Afficher les premières lignes
print(df.head())

# Informations sur le dataset
print(df.info())

# Statistiques descriptives
print(df.describe())

# Statistiques pour une colonne spécifique
colonne = df['Value']  # Adapter selon vos données

print(f"Moyenne: {colonne.mean():.2f}")
print(f"Médiane: {colonne.median():.2f}")
print(f"Mode: {colonne.mode()[0]:.2f}")
print(f"Écart-type: {colonne.std():.2f}")
print(f"Variance: {colonne.var():.2f}")
print(f"Min: {colonne.min():.2f}")
print(f"Max: {colonne.max():.2f}")

# Quartiles
print(f"Q1 (25%): {colonne.quantile(0.25):.2f}")
print(f"Q2 (50% - Médiane): {colonne.quantile(0.50):.2f}")
print(f"Q3 (75%): {colonne.quantile(0.75):.2f}")
print(f"IQR: {colonne.quantile(0.75) - colonne.quantile(0.25):.2f}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Charger un dataset en ligne (exemple : ventes d'une entreprise)
# gdp.csv : nom fichier PIB
# stocké sur githib
url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv" #jeux de données
df = pd.read_csv(url)

# Afficher les premières lignes
print(df.head())

# Informations sur le dataset
print(df.info())

# Statistiques descriptives
print(df.describe())

# Statistiques pour une colonne spécifique
colonne = df['Value']  # Adapter selon vos données

print(f"Moyenne: {colonne.mean():.2f}")
print(f"Médiane: {colonne.median():.2f}")
print(f"Mode: {colonne.mode()[0]:.2f}")
print(f"Écart-type: {colonne.std():.2f}")
print(f"Variance: {colonne.var():.2f}")
print(f"Min: {colonne.min():.2f}")
print(f"Max: {colonne.max():.2f}")

# Quartiles
print(f"Q1 (25%): {colonne.quantile(0.25):.2f}")
print(f"Q2 (50% - Médiane): {colonne.quantile(0.50):.2f}")
print(f"Q3 (75%): {colonne.quantile(0.75):.2f}")
print(f"IQR: {colonne.quantile(0.75) - colonne.quantile(0.25):.2f}")

"""### Histogram of GDP 'Value'

Let's start by visualizing the distribution of the 'Value' (GDP) column using a histogram. This will help us understand the frequency of different GDP ranges.
"""

plt.figure(figsize=(10, 6))
sns.histplot(df['Value'], kde=True, bins=50)
plt.title('Distribution of GDP Value')
plt.xlabel('GDP Value')
plt.ylabel('Frequency')
plt.xscale('log') # Use a log scale for better visualization due to large range
plt.show()

"""### GDP Trend Over Years for Top Countries

Next, let's look at the GDP trend over the years. Given the vast number of entries, I will focus on the top 5 countries by their total GDP across all years to illustrate the temporal changes.
"""

# Calculate total GDP for each country to identify top countries
top_countries = df.groupby('Country Name')['Value'].sum().nlargest(5).index

# Filter the DataFrame for these top countries
df_top_countries = df[df['Country Name'].isin(top_countries)]

plt.figure(figsize=(14, 7))
sns.lineplot(data=df_top_countries, x='Year', y='Value', hue='Country Name', marker='o')
plt.title('GDP Trend Over Years for Top 5 Countries')
plt.xlabel('Year')
plt.ylabel('GDP Value')
plt.yscale('log') # Using log scale for better visualization
plt.grid(True)
plt.legend(title='Country')
plt.show()

"""### Box Plot of GDP by Year

Finally, a box plot can give us insights into the distribution of GDP values for each year, showing the median, quartiles, and potential outliers.
"""

plt.figure(figsize=(16, 8))
sns.boxplot(data=df, x='Year', y='Value')
plt.title('Distribution of GDP Value by Year')
plt.xlabel('Year')
plt.ylabel('GDP Value')
plt.yscale('log') # Using log scale due to wide range of GDP values
plt.xticks(rotation=90)
plt.grid(True, axis='y')
plt.show()

from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets

# metadata
print(heart_disease.metadata)

# variable information
print(heart_disease.variables)

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
heart_disease = fetch_ucirepo(id=45)

# data (as pandas dataframes)
X = heart_disease.data.features
y = heart_disease.data.targets

# Display the first few rows of the features and target
print("Features (X) head:")
display(X.head())
print("Target (y) head:")
display(y.head())

"""### Graphical Presentation of Heart Disease Dataset

Let's start by visualizing the distribution of a key feature like 'age' and the distribution of the target variable 'num' (heart disease presence).
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 5))

# Histogram of Age
plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
sns.histplot(X['age'], kde=True)
plt.title('Distribution of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')

# Count plot of the target variable (Heart Disease Presence)
plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
sns.countplot(x=y['num'])
plt.title('Heart Disease Presence (0 = No, 1-4 = Yes)')
plt.xlabel('Heart Disease')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1, 2, 3, 4], labels=['No Disease', 'Type 1', 'Type 2', 'Type 3', 'Type 4'])

plt.tight_layout()
plt.show()



